export default {
  421: 'Service not available, closing control connection. This may be a reply to any command if the service knows it must shut down.',
  425: "Can't open data connection.",
  426: 'Connection closed; transfer aborted.',
  430: 'Invalid username or password.',
  434: 'Requested host unavailable.',
  450: 'Requested file action not taken.',
  451: 'Requested action aborted. Local error in processing.',
  452: 'Requested action not taken. Insufficient storage space in system.File unavailable (e.g., file busy).',
  501: 'Syntax error in parameters or arguments.',
  502: 'Command not implemented.',
  503: 'Bad sequence of commands.',
  504: 'Command not implemented for that parameter.',
  530: 'Not logged in.',
  532: 'Need account for storing files.',
  534: 'Could Not Connect to Server - Policy Requires SSL',
  550: 'Requested action not taken. File unavailable (e.g. file not found, no access).',
  551: 'Requested action aborted. Page type unknown.',
  552: 'Requested file action aborted. Exceeded storage allocation (for current directory or dataset).',
  553: 'Requested action not taken. File name not allowed.',
  10054:
    'Connection reset by peer. The connection was forcibly closed by the remote host.',
  10060: 'Cannot connect to remote server.',
  10061:
    'Cannot connect to remote server. The connection is actively refused by the server.',
  10066: 'Directory not empty.',
  10068: 'Too many users, server is full.',
};
