export default {
  'index.html':
    '<!DOCTYPE html>\n<html lang="en">\n\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <meta http-equiv="X-UA-Compatible" content="ie=edge">\n  <script src="https://unpkg.com/systemjs@0.21.6/dist/system.js"></script>\n  <title><%name%></title>\n</head>\n\n<body>\n  <noscript>\n    <strong>We\'re sorry but <%name%> doesn\'t work properly without JavaScript enabled.\n      Please enable it to continue.</strong>\n  </noscript>\n  <div id="app"><%name%> is loading...</div>\n  <script src="systemjs.config.js"></script>\n</body>\n\n</html>',
  'systemjs.config.js':
    "SystemJS.config({\n  baseURL:'https://unpkg.com/',\n  defaultExtension: true,\n  meta: {\n    '*.vue': {\n      'loader': 'vue-loader'\n    }\n  },\n  map: {\n    'plugin-babel': 'systemjs-plugin-babel@latest/plugin-babel.js',\n    'systemjs-babel-build': 'systemjs-plugin-babel@latest/systemjs-babel-browser.js',\n    'vue-loader': 'systemjs-vue-loader@latest',\n    'vue': '/vue@latest/dist/vue.cjs.prod.js',\n    'vue-template-compiler': 'vue-template-compiler@latest'\n  },\n  transpiler: 'plugin-babel'\n});\n\nSystemJS.import('./src/main.js')\n  .catch(console.error.bind(console));",
  'src/main.js':
    "import Vue from 'vue'\nimport App from './App.vue'\n\nnew Vue({\n  render: h => h(App)\n}).$mount('#app')",
  'src/App.vue':
    '<template>\n  <div id="app">\n    <img alt="Vue logo" src="./assets/logo.svg" />\n    <HelloWorld msg="Welcome to <%name%>." />\n  </div>\n</template>\n\n<script>\nimport HelloWorld from "./components/HelloWorld.vue";\n\nexport default {\n  name: "App",\n  components: {\n    HelloWorld\n  }\n};\n</script>\n\n<style>\n#app {\n  font-family: Avenir, Helvetica, Arial, sans-serif;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n  text-align: center;\n  color: #2c3e50;\n  margin-top: 60px;\n}\n\n#app img {\n  height: 200px;\n  width: 200px;\n}\n</style>\n',
  'src/components/HelloWorld.vue':
    '<template>\n  <div class="hello">\n    <h1>{{ msg }}</h1>\n    <h3>Essential Links</h3>\n    <ul>\n      <li><a href="https://vuejs.org" target="_blank" rel="noopener">Core Docs</a></li>\n      <li><a href="https://forum.vuejs.org" target="_blank" rel="noopener">Forum</a></li>\n      <li><a href="https://chat.vuejs.org" target="_blank" rel="noopener">Community Chat</a></li>\n      <li><a href="https://twitter.com/vuejs" target="_blank" rel="noopener">Twitter</a></li>\n      <li><a href="https://news.vuejs.org" target="_blank" rel="noopener">News</a></li>\n    </ul>\n    <h3>Ecosystem</h3>\n    <ul>\n      <li><a href="https://router.vuejs.org" target="_blank" rel="noopener">vue-router</a></li>\n      <li><a href="https://vuex.vuejs.org" target="_blank" rel="noopener">vuex</a></li>\n      <li><a href="https://github.com/vuejs/vue-devtools#vue-devtools" target="_blank" rel="noopener">vue-devtools</a></li>\n      <li><a href="https://vue-loader.vuejs.org" target="_blank" rel="noopener">vue-loader</a></li>\n      <li><a href="https://github.com/vuejs/awesome-vue" target="_blank" rel="noopener">awesome-vue</a></li>\n    </ul>\n  </div>\n</template>\n\n<script>\nexport default {\n  name: \'HelloWorld\',\n  props: {\n    msg: String\n  }\n}\n</script>\n\n<!-- Add "scoped" attribute to limit CSS to this component only -->\n<style scoped>\nh3 {\n  margin: 40px 0 0;\n}\nul {\n  list-style-type: none;\n  padding: 0;\n}\nli {\n  display: inline-block;\n  margin: 0 10px;\n}\na {\n  color: #42b983;\n}\n</style>',
  'assets/logo.svg':
    '<svg viewBox="0 0 256 221" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin meet"><path d="M204.8 0H256L128 220.8 0 0h97.92L128 51.2 157.44 0h47.36z" fill="#41B883"/><path d="M0 0l128 220.8L256 0h-51.2L128 132.48 50.56 0H0z" fill="#41B883"/><path d="M50.56 0L128 133.12 204.8 0h-47.36L128 51.2 97.92 0H50.56z" fill="#35495E"/></svg>',
};
